title: NGC Summary Archive
author: Jesse Talavera-Greenberg
email: jessetalavera@aol.com
description: > # this means to ignore newlines until "twitter_username:"
  An unofficial archive of the information once hosted on the National
  Guideline Clearinghouse.

repository: JesseTG/ngc-archive

# social links
twitter_username: JesseT_G
github_username:  JesseTG
rss: rss

page_paths:
  - summary
  - about
  - disclaimers

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

exclude:
  - .vscode
  - .git
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - _summary/convert-to-markdown.sh
  - _summary/convert-to-markdown.py
  - _summary/.git
  - _summary/.gitignore
  - _summary/README.md
  - _summary/requirements.txt
  - _summary/getter.py
  - _summary/expert-commentary
  - _summary/matrix

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-redirect-from
 - jekyll-optional-front-matter
 
collections:
  summary:
    collections_dir: _summary
    output: true
    permalink: /:collection/:path/

defaults:
  # _summary
  - scope:
      path: ""
      type: summary
    values:
      layout: page
      author_profile: false
      share: true
